//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socionic_tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class answers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public answers()
        {
            this.question_result = new HashSet<question_result>();
        }
    
        public int id_answer { get; set; }
        public int id_question { get; set; }
        public string answer { get; set; }
        public int weight { get; set; }
    
        public virtual questions questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_result> question_result { get; set; }
    }
}
