//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socionic_tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_range
    {
        public int id_range { get; set; }
        public int id_test { get; set; }
        public int range_top { get; set; }
        public int range_bottom { get; set; }
        public int id_recommendation { get; set; }
    
        public virtual recommendations recommendations { get; set; }
        public virtual tests tests { get; set; }
    }
}
