//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socionic_tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_range
    {
        public int id_range { get; set; }
        public int id_test { get; set; }
        public int range_top { get; set; }
        public int range_bottom { get; set; }
        public int id_recommendation { get; set; }
    
        public virtual recommendations recommendations { get; set; }
        public virtual tests tests { get; set; }
    }
}
